from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd + '/include']
LIBPATH = [cwd + '/lib/x86']
LIBS    = ['SDL', 'SDLmain']

group = DefineGroup('rtgui', src, depend = ['RT_USING_RTGUI'], CPPPATH = CPPPATH, LIBPATH=LIBPATH, LIBS=LIBS)

Return('group')
